/// Data model for an I-Ching Hexagram (64 Gua).
/// The 'binary' string is 6-bit: S2-R3 | S2-R2 | S2-R1 | S1-R3 | S1-R2 | S1-R1
/// Where S1 = Stage 1, S2 = Stage 2, R1 = Round 1 (bottom line).
class Gua64Details {
  final String binary;           // e.g., '010011'
  final String symbol;           // Unicode hexagram symbol (U+4DC0 to U+4DFF)
  final String name_zh;          // 卦名 (e.g., 涣)
  final String name_pinyin_std;  // standard Pinyin (e.g., huan)
  final String name_pinyin_trad; // traditional Pinyin (e.g., Huan)
  final String stack_zh;         // 下坎上巽
  final String explanation_zh;   // 亨。王假有庙，利涉大川，利贞。
  final String luck_zh;          // 亨通，涣散重生
  final String sign_zh;          // Fortune sign: 大吉, 吉, 平, 小凶, 凶, 大凶
  final String name_en_meaning;  // English meaning (e.g., Dispersion)
  final String stack_en;         // Bottom kan Top xun
  final String explanation_en;   // English explanation
  final String luck_en;          // English luck interpretation
  final String sign_en;          // Fortune sign: Very Auspicious, Auspicious, Neutral, Slightly Inauspicious, Inauspicious, Very Inauspicious

  const Gua64Details({
    required this.binary,
    required this.symbol,
    required this.name_zh,
    required this.name_pinyin_std,
    required this.name_pinyin_trad,
    required this.stack_zh,
    required this.explanation_zh,
    required this.luck_zh,
    required this.sign_zh,
    required this.name_en_meaning,
    required this.stack_en,
    required this.explanation_en,
    required this.luck_en,
    required this.sign_en,
  });

  @override
  String toString() => '$name_zh $symbol ($name_pinyin_std - $name_en_meaning)';
}

/// A static class to hold and provide all 64 Gua mappings.
class Gua64Data {
  /// Maps a 6-bit binary string to the corresponding Hexagram (64 Gua).
  /// Sorted by binary value (000000 to 111111) with proper trigram ordering.
  static const Map<String, Gua64Details> Gua64Map = {
    // 000000 - 000111: 下坤上...
    '000000': Gua64Details(
      binary: '000000',	// U+4DC1
      symbol: '䷁', 
      name_zh: "坤",
      name_pinyin_std: "kun",
      name_pinyin_trad: "K'un",
      stack_zh: "下坤上坤",
      explanation_zh: "元亨，利牝马之贞。君子有攸往，先迷后得主，利西南得朋，东北丧朋。安贞吉。",
      luck_zh: "大吉，顺应自然",
      sign_zh: "大吉",
      name_en_meaning: "The Receptive",
      stack_en: "Bottom kun Top kun",
      explanation_en: "Earth over Earth, ultimate receptivity and yielding.",
      luck_en: "Success through adaptability and nurturing support.",
      sign_en: "Very Auspicious",
    ),
    '000001': Gua64Details(
      binary: '000001',
      symbol: '䷖',	// U+4DD6
      name_zh: "剥",
      name_pinyin_std: "bo",
      name_pinyin_trad: "Po",
      stack_zh: "下坤上艮",
      explanation_zh: "不利有攸往。",
      luck_zh: "凶，不利于有所行动",
      sign_zh: "凶",
      name_en_meaning: "Stripping",
      stack_en: "Bottom kun Top gen",
      explanation_en: "Mountain over Earth, decay and peeling away.",
      luck_en: "Waiting during periods of decline and decay.",
      sign_en: "Inauspicious",
    ),
    '000010': Gua64Details(
      binary: '000010',
      symbol: '䷇',  // U+4DC7
      name_zh: "比",
      name_pinyin_std: "bi",
      name_pinyin_trad: "Pi",
      stack_zh: "下坤上坎",
      explanation_zh: "吉。原筮元永贞，无咎。不宁方来，后夫凶。",
      luck_zh: "吉，亲附则吉",
      sign_zh: "吉",
      name_en_meaning: "Union",
      stack_en: "Bottom kun Top kan",
      explanation_en: "Water over Earth, flowing together in union.",
      luck_en: "Success through alliances and cooperation.",
      sign_en: "Auspicious",
    ),
    '000011': Gua64Details(
      binary: '000011',
      symbol: '䷓',
      name_zh: "观",
      name_pinyin_std: "guan",
      name_pinyin_trad: "Kuan",
      stack_zh: "下坤上巽",
      explanation_zh: "盥而不荐，有孚颙若。",
      luck_zh: "平，观察感悟，诚敬则吉",
      sign_zh: "平",
      name_en_meaning: "Contemplation",
      stack_en: "Bottom kun Top xun",
      explanation_en: "Wind over Earth, observing and contemplating.",
      luck_en: "Success through careful observation and study.",
      sign_en: "Neutral",
    ),
    '000100': Gua64Details(
      binary: '000100',
      symbol: '䷏',
      name_zh: "豫",
      name_pinyin_std: "yu",
      name_pinyin_trad: "Yü",
      stack_zh: "下坤上震",
      explanation_zh: "利建侯行师。",
      luck_zh: "吉，利于建立功业",
      sign_zh: "吉",
      name_en_meaning: "Enthusiasm",
      stack_en: "Bottom kun Top zhen",
      explanation_en: "Thunder over Earth, enthusiasm and harmony.",
      luck_en: "Success through enthusiasm and harmonious action.",
      sign_en: "Auspicious",
    ),
    '000101': Gua64Details(
      binary: '000101',
      symbol: '䷢',
      name_zh: "晋",
      name_pinyin_std: "jin",
      name_pinyin_trad: "Chin",
      stack_zh: "下坤上离",
      explanation_zh: "康侯用锡马蕃庶，昼日三接。",
      luck_zh: "吉，前进昌盛",
      sign_zh: "吉",
      name_en_meaning: "Progress",
      stack_en: "Bottom kun Top li",
      explanation_en: "Fire over Earth, advancement with clarity.",
      luck_en: "Advancement and progress illuminated by clarity.",
      sign_en: "Auspicious",
    ),
    '000110': Gua64Details(
      binary: '000110',
      symbol: '䷬',
      name_zh: "萃",
      name_pinyin_std: "cui",
      name_pinyin_trad: "Ts'ui",
      stack_zh: "下坤上兑",
      explanation_zh: "亨。王假有庙，利见大人，亨，利贞。用大牲吉，利有攸往。",
      luck_zh: "亨通，聚集致亨",
      sign_zh: "大吉",
      name_en_meaning: "Gathering Together",
      stack_en: "Bottom kun Top dui",
      explanation_en: "Lake over Earth, gathering and assembly.",
      luck_en: "Strength through gathering and unity.",
      sign_en: "Very Auspicious",
    ),
    '000111': Gua64Details(
      binary: '000111',
      symbol: '䷋',
      name_zh: "否",
      name_pinyin_std: "pi",
      name_pinyin_trad: "P'i",
      stack_zh: "下坤上乾",
      explanation_zh: "否之匪人，不利君子贞，大往小来。",
      luck_zh: "凶，闭塞不通",
      sign_zh: "凶",
      name_en_meaning: "Stagnation",
      stack_en: "Bottom kun Top qian",
      explanation_en: "Heaven over Earth, standstill and blockage.",
      luck_en: "Period of stagnation requiring patience.",
      sign_en: "Inauspicious",
    ),

    // 001000 - 001111: 下艮上...
    '001000': Gua64Details(
      binary: '001000',
      symbol: '䷎',
      name_zh: "谦",
      name_pinyin_std: "qian",
      name_pinyin_trad: "Ch'ien",
      stack_zh: "下艮上坤",
      explanation_zh: "亨，君子有终。",
      luck_zh: "大吉，谦逊终吉",
      sign_zh: "大吉",
      name_en_meaning: "Modesty",
      stack_en: "Bottom gen Top kun",
      explanation_en: "Earth over Mountain, humility brings honor.",
      luck_en: "Success through humility and modesty.",
      sign_en: "Very Auspicious",
    ),
    '001001': Gua64Details(
      binary: '001001',
      symbol: '䷳',
      name_zh: "艮",
      name_pinyin_std: "gen",
      name_pinyin_trad: "Ken",
      stack_zh: "下艮上艮",
      explanation_zh: "艮其背，不获其身，行其庭，不见其人，无咎。",
      luck_zh: "平，适时静止",
      sign_zh: "平",
      name_en_meaning: "Keeping Still",
      stack_en: "Bottom gen Top gen",
      explanation_en: "Mountain over Mountain, stillness and meditation.",
      luck_en: "Success through stillness and proper timing.",
      sign_en: "Neutral",
    ),
    '001010': Gua64Details(
      binary: '001010',
      symbol: '䷦',
      name_zh: "蹇",
      name_pinyin_std: "jian",
      name_pinyin_trad: "Chien",
      stack_zh: "下艮上坎",
      explanation_zh: "利西南，不利东北，利见大人，贞吉。",
      luck_zh: "凶中带吉，遇险知止",
      sign_zh: "小凶",
      name_en_meaning: "Obstruction",
      stack_en: "Bottom gen Top kan",
      explanation_en: "Water over Mountain, obstruction and difficulty.",
      luck_en: "Overcoming obstacles with help and wisdom.",
      sign_en: "Slightly Inauspicious",
    ),
    '001011': Gua64Details(
      binary: '001011',
      symbol: '䷴',
      name_zh: "渐",
      name_pinyin_std: "jian",
      name_pinyin_trad: "Chien",
      stack_zh: "下艮上巽",
      explanation_zh: "女归吉，利贞。",
      luck_zh: "吉，渐进则吉",
      sign_zh: "吉",
      name_en_meaning: "Gradual Progress",
      stack_en: "Bottom gen Top xun",
      explanation_en: "Wind over Mountain, gradual advance.",
      luck_en: "Success through gradual, steady progress.",
      sign_en: "Auspicious",
    ),
    '001100': Gua64Details(
      binary: '001100',
      symbol: '䷽',
      name_zh: "小过",
      name_pinyin_std: "xiaoguo",
      name_pinyin_trad: "Hsiao Kuo",
      stack_zh: "下艮上震",
      explanation_zh: "亨，利贞，可小事，不可大事。",
      luck_zh: "小凶，行动有度",
      sign_zh: "小凶",
      name_en_meaning: "Small Exceeding",
      stack_en: "Bottom gen Top zhen",
      explanation_en: "Thunder over Mountain, minor excesses.",
      luck_en: "Minor adjustments needed for small excesses.",
      sign_en: "Slightly Inauspicious",
    ),
    '001101': Gua64Details(
      binary: '001101',
      symbol: '䷷',
      name_zh: "旅",
      name_pinyin_std: "lv",
      name_pinyin_trad: "Lu",
      stack_zh: "下艮上离",
      explanation_zh: "小亨，旅贞吉。",
      luck_zh: "小凶，旅居守正则吉",
      sign_zh: "小凶",
      name_en_meaning: "The Wanderer",
      stack_en: "Bottom gen Top li",
      explanation_en: "Fire over Mountain, the traveler's journey.",
      luck_en: "Success through adaptability while traveling.",
      sign_en: "Slightly Inauspicious",
    ),
    '001110': Gua64Details(
      binary: '001110',
      symbol: '䷞',  
      name_zh: "咸",
      name_pinyin_std: "xian",
      name_pinyin_trad: "Hsien",
      stack_zh: "下艮上兑",
      explanation_zh: "亨，利贞，取女吉。",
      luck_zh: "吉，感应亨通",
      sign_zh: "吉",
      name_en_meaning: "Influence",
      stack_en: "Bottom gen Top dui",
      explanation_en: "Lake over Mountain, mutual influence and attraction.",
      luck_en: "Success through mutual influence and attraction.",
      sign_en: "Auspicious",
    ),
    '001111': Gua64Details(
      binary: '001111',
      symbol: '䷠',
      name_zh: "遁",
      name_pinyin_std: "dun",
      name_pinyin_trad: "Tun",
      stack_zh: "下艮上乾",
      explanation_zh: "亨，小利贞。",
      luck_zh: "吉，退避亨通",
      sign_zh: "吉",
      name_en_meaning: "Retreat",
      stack_en: "Bottom gen Top qian",
      explanation_en: "Heaven over Mountain, strategic withdrawal.",
      luck_en: "Success through timely retreat.",
      sign_en: "Auspicious",
    ),

    // 010000 - 010111: 下坎上...
    '010000': Gua64Details(
      binary: '010000',
      symbol: '䷆', 
      name_zh: "师",
      name_pinyin_std: "shi",
      name_pinyin_trad: "Shih",
      stack_zh: "下坎上坤",
      explanation_zh: "贞丈人吉，无咎。",
      luck_zh: "平，出师以正",
      sign_zh: "平",
      name_en_meaning: "The Army",
      stack_en: "Bottom kan Top kun",
      explanation_en: "Earth over Water, army mobilization.",
      luck_en: "Success through organized effort and strong leadership.",
      sign_en: "Neutral",
    ),
    '010001': Gua64Details(
      binary: '010001',
      symbol: '䷃', 
      name_zh: "蒙",
      name_pinyin_std: "meng",
      name_pinyin_trad: "Meng",
      stack_zh: "下坎上艮",
      explanation_zh: "亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。",
      luck_zh: "亨通，启蒙之道",
      sign_zh: "吉",
      name_en_meaning: "Youthful Folly",
      stack_en: "Bottom kan Top gen",
      explanation_en: "Mountain over Water, youthful inexperience.",
      luck_en: "Learning and enlightenment through guidance.",
      sign_en: "Auspicious",
    ),
    '010010': Gua64Details(
      binary: '010010',
      symbol: '䷜',  
      name_zh: "坎",
      name_pinyin_std: "kan",
      name_pinyin_trad: "K'an",
      stack_zh: "下坎上坎",
      explanation_zh: "习坎，有孚，维心亨，行有尚。",
      luck_zh: "大凶，险中有信则可亨",
      sign_zh: "大凶",
      name_en_meaning: "The Abysmal",
      stack_en: "Bottom kan Top kan",
      explanation_en: "Water over Water, abyss and repeated danger.",
      luck_en: "Endurance through repeated difficulties.",
      sign_en: "Very Inauspicious",
    ),
    '010011': Gua64Details(
      binary: '010011',
      symbol: '䷺',
      name_zh: "涣",
      name_pinyin_std: "huan",
      name_pinyin_trad: "Huan",
      stack_zh: "下坎上巽",
      explanation_zh: "亨。王假有庙，利涉大川，利贞。",
      luck_zh: "亨通，涣散重生",
      sign_zh: "吉",
      name_en_meaning: "Dispersion",
      stack_en: "Bottom kan Top xun",
      explanation_en: "Wind over Water, dissolving and dispersion.",
      luck_en: "Dissolving difficulties and starting anew.",
      sign_en: "Auspicious",
    ),
    '010100': Gua64Details(
      binary: '010100',
      symbol: '䷧', 
      name_zh: "解",
      name_pinyin_std: "xie",
      name_pinyin_trad: "Chieh",
      stack_zh: "下坎上震",
      explanation_zh: "利西南，无所往，其来复吉。有攸往，夙吉。",
      luck_zh: "吉，险难解除",
      sign_zh: "吉",
      name_en_meaning: "Deliverance",
      stack_en: "Bottom kan Top zhen",
      explanation_en: "Thunder over Water, liberation from tension.",
      luck_en: "Relief and liberation from constraints.",
      sign_en: "Auspicious",
    ),
    '010101': Gua64Details(
      binary: '010101',
      symbol: '䷿', 
      name_zh: "未济",
      name_pinyin_std: "weiji",
      name_pinyin_trad: "Wei Chi",
      stack_zh: "下坎上离",
      explanation_zh: "亨，小狐汔济，濡其尾，无攸利。",
      luck_zh: "事未成，慎终如始",
      sign_zh: "小凶",
      name_en_meaning: "Before Completion",
      stack_en: "Bottom kan Top li",
      explanation_en: "Fire over Water, incompletion and transition.",
      luck_en: "Not yet completed, continued effort needed.",
      sign_en: "Slightly Inauspicious",
    ),
    '010110': Gua64Details(
      binary: '010110',
      symbol: '䷮',
      name_zh: "困",
      name_pinyin_std: "kun",
      name_pinyin_trad: "K'un",
      stack_zh: "下坎上兑",
      explanation_zh: "亨，贞，大人吉，无咎，有言不信。",
      luck_zh: "大凶，困境守德则亨",
      sign_zh: "大凶",
      name_en_meaning: "Oppression",
      stack_en: "Bottom kan Top dui",
      explanation_en: "Lake over Water,困境 and hardship.",
      luck_en: "Enduring hardship with integrity leads to relief.",
      sign_en: "Very Inauspicious",
    ),
    '010111': Gua64Details(
      binary: '010111',
      symbol: '䷅',  
      name_zh: "讼",
      name_pinyin_std: "song",
      name_pinyin_trad: "Sung",
      stack_zh: "下坎上乾",
      explanation_zh: "有孚，窒惕，中吉，终凶。利见大人，不利涉大川。",
      luck_zh: "凶，争讼终凶",
      sign_zh: "凶",
      name_en_meaning: "Conflict",
      stack_en: "Bottom kan Top qian",
      explanation_en: "Heaven over Water, legal conflict and disputes.",
      luck_en: "Resolution through compromise rather than winning.",
      sign_en: "Inauspicious",
    ),

    // 011000 - 011111: 下巽上...
    '011000': Gua64Details(
      binary: '011000',
      symbol: '䷭',
      name_zh: "升",
      name_pinyin_std: "sheng",
      name_pinyin_trad: "Sheng",
      stack_zh: "下巽上坤",
      explanation_zh: "元亨，用见大人，勿恤，南征吉。",
      luck_zh: "大吉，上升之势",
      sign_zh: "大吉",
      name_en_meaning: "Ascending",
      stack_en: "Bottom xun Top kun",
      explanation_en: "Earth over Wind, gradual ascent.",
      luck_en: "Steady progress through gradual advancement.",
      sign_en: "Very Auspicious",
    ),
    '011001': Gua64Details(
      binary: '011001',
      symbol: '䷑',
      name_zh: "蛊",
      name_pinyin_std: "gu",
      name_pinyin_trad: "Ku",
      stack_zh: "下巽上艮",
      explanation_zh: "元亨，利涉大川。先甲三日，后甲三日。",
      luck_zh: "亨通，整治乱局",
      sign_zh: "吉",
      name_en_meaning: "Decay",
      stack_en: "Bottom xun Top gen",
      explanation_en: "Mountain over Wind, dealing with decay.",
      luck_en: "Correcting decay and reforming what's spoiled.",
      sign_en: "Auspicious",
    ),
    '011010': Gua64Details(
      binary: '011010',
      symbol: '䷯',
      name_zh: "井",
      name_pinyin_std: "jing",
      name_pinyin_trad: "Ching",
      stack_zh: "下巽上坎",
      explanation_zh: "改邑不改井，无丧无得，往来井井。",
      luck_zh: "平，修身养德",
      sign_zh: "平",
      name_en_meaning: "The Well",
      stack_en: "Bottom xun Top kan",
      explanation_en: "Water over Wind, the well as stable resource.",
      luck_en: "Stable resources and nourishment available.",
      sign_en: "Neutral",
    ),
    '011011': Gua64Details(
      binary: '011011',
      symbol: '䷸', 
      name_zh: "巽",
      name_pinyin_std: "xun",
      name_pinyin_trad: "Sun",
      stack_zh: "下巽上巽",
      explanation_zh: "小亨，利有攸往，利见大人。",
      luck_zh: "小亨，顺从之道",
      sign_zh: "小吉",
      name_en_meaning: "The Gentle",
      stack_en: "Bottom xun Top xun",
      explanation_en: "Wind over Wind, gentle penetration.",
      luck_en: "Success through gentle, yielding influence.",
      sign_en: "Slightly Auspicious",
    ),
    '011100': Gua64Details(
      binary: '011100',
      symbol: '䷟', 
      name_zh: "恒",
      name_pinyin_std: "heng",
      name_pinyin_trad: "Heng",
      stack_zh: "下巽上震",
      explanation_zh: "亨，无咎，利贞，利有攸往。",
      luck_zh: "吉，持恒致亨",
      sign_zh: "吉",
      name_en_meaning: "Duration",
      stack_en: "Bottom xun Top zhen",
      explanation_en: "Thunder over Wind, perseverance through time.",
      luck_en: "Success through persistence and endurance.",
      sign_en: "Auspicious",
    ),
    '011101': Gua64Details(
      binary: '011101',
      symbol: '䷱',
      name_zh: "鼎",
      name_pinyin_std: "ding",
      name_pinyin_trad: "Ting",
      stack_zh: "下巽上离",
      explanation_zh: "元吉，亨。",
      luck_zh: "大吉，鼎新稳固",
      sign_zh: "大吉",
      name_en_meaning: "The Cauldron",
      stack_en: "Bottom xun Top li",
      explanation_en: "Fire over Wind, the cauldron of transformation.",
      luck_en: "Stability and nourishment through transformation.",
      sign_en: "Very Auspicious",
    ),
    '011110': Gua64Details(
      binary: '011110',
      symbol: '䷛', 
      name_zh: "大过",
      name_pinyin_std: "daguo",
      name_pinyin_trad: "Ta Kuo",
      stack_zh: "下巽上兑",
      explanation_zh: "栋桡，利有攸往，亨。",
      luck_zh: "大凶，过犹不及",
      sign_zh: "大凶",
      name_en_meaning: "Great Exceeding",
      stack_en: "Bottom xun Top dui",
      explanation_en: "Lake over Wind, critical excess.",
      luck_en: "Major adjustment needed at critical point.",
      sign_en: "Very Inauspicious",
    ),
    '011111': Gua64Details(
      binary: '011111',
      symbol: '䷫', 
      name_zh: "姤",
      name_pinyin_std: "gou",
      name_pinyin_trad: "Kou",
      stack_zh: "下巽上乾",
      explanation_zh: "女壮，勿用取女。",
      luck_zh: "凶，不期而遇",
      sign_zh: "凶",
      name_en_meaning: "Coming to Meet",
      stack_en: "Bottom xun Top qian",
      explanation_en: "Heaven over Wind, unexpected encounter.",
      luck_en: "Unexpected encounters, be cautious.",
      sign_en: "Inauspicious",
    ),

    // 100000 - 100111: 下震上...
    '100000': Gua64Details(
      binary: '100000',
      symbol: '䷗', 
      name_zh: "复",
      name_pinyin_std: "fu",
      name_pinyin_trad: "Fu",
      stack_zh: "下震上坤",
      explanation_zh: "亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往。",
      luck_zh: "吉，一阳来复",
      sign_zh: "吉",
      name_en_meaning: "Return",
      stack_en: "Bottom zhen Top kun",
      explanation_en: "Earth over Thunder, return to correct path.",
      luck_en: "Return to the right path, new beginnings.",
      sign_en: "Auspicious",
    ),
    '100001': Gua64Details(
      binary: '100001',
      symbol: '䷚', 
      name_zh: "颐",
      name_pinyin_std: "yi",
      name_pinyin_trad: "I",
      stack_zh: "下震上艮",
      explanation_zh: "贞吉。观颐，自求口实。",
      luck_zh: "吉，养正则吉",
      sign_zh: "吉",
      name_en_meaning: "Nourishment",
      stack_en: "Bottom zhen Top gen",
      explanation_en: "Mountain over Thunder, self-nourishment.",
      luck_en: "Success through self-cultivation and nourishment.",
      sign_en: "Auspicious",
    ),
    '100010': Gua64Details(
      binary: '100010',
      symbol: '䷂', 
      name_zh: "屯",
      name_pinyin_std: "zhun",
      name_pinyin_trad: "Chun",
      stack_zh: "下震上坎",
      explanation_zh: "元亨，利贞。勿用有攸往，利建侯。",
      luck_zh: "吉，创始维艰",
      sign_zh: "吉",
      name_en_meaning: "Difficulty at the Beginning",
      stack_en: "Bottom zhen Top kan",
      explanation_en: "Water over Thunder, initial difficulty.",
      luck_en: "Patience needed during initial challenges.",
      sign_en: "Auspicious",
    ),
    '100011': Gua64Details(
      binary: '100011',
      symbol: '䷩', 
      name_zh: "益",
      name_pinyin_std: "yi",
      name_pinyin_trad: "I",
      stack_zh: "下震上巽",
      explanation_zh: "利有攸往，利涉大川。",
      luck_zh: "大吉，增益他人",
      sign_zh: "大吉",
      name_en_meaning: "Increase",
      stack_en: "Bottom zhen Top xun",
      explanation_en: "Wind over Thunder, increase and benefit.",
      luck_en: "Growth and increase through benefit to others.",
      sign_en: "Very Auspicious",
    ),
    '100100': Gua64Details(
      binary: '100100',
      symbol: '䷲', 
      name_zh: "震",
      name_pinyin_std: "zhen",
      name_pinyin_trad: "Chen",
      stack_zh: "下震上震",
      explanation_zh: "亨。震来虩虩，笑言哑哑，震惊百里，不丧匕鬯。",
      luck_zh: "亨通，临危不惧",
      sign_zh: "吉",
      name_en_meaning: "The Arousing",
      stack_en: "Bottom zhen Top zhen",
      explanation_en: "Thunder over Thunder, shock and awakening.",
      luck_en: "Awakening through shock, maintaining composure.",
      sign_en: "Auspicious",
    ),
    '100101': Gua64Details(
      binary: '100101',
      symbol: '䷔',
      name_zh: "噬嗑",
      name_pinyin_std: "shihe",
      name_pinyin_trad: "Shih Ho",
      stack_zh: "下震上离",
      explanation_zh: "亨，利用狱。",
      luck_zh: "亨通，消除障碍",
      sign_zh: "吉",
      name_en_meaning: "Biting Through",
      stack_en: "Bottom zhen Top li",
      explanation_en: "Fire over Thunder, biting through obstacles.",
      luck_en: "Resolving conflicts by facing them directly.",
      sign_en: "Auspicious",
    ),
    '100110': Gua64Details(
      binary: '100110',
      symbol: '䷐', 
      name_zh: "随",
      name_pinyin_std: "sui",
      name_pinyin_trad: "Sui",
      stack_zh: "下震上兑",
      explanation_zh: "元亨，利贞，无咎。",
      luck_zh: "大吉，随顺时势",
      sign_zh: "大吉",
      name_en_meaning: "Following",
      stack_en: "Bottom zhen Top dui",
      explanation_en: "Lake over Thunder, following naturally.",
      luck_en: "Success through adaptation and following flow.",
      sign_en: "Very Auspicious",
    ),
    '100111': Gua64Details(
      binary: '100111',
      symbol: '䷘',
      name_zh: "无妄",
      name_pinyin_std: "wuwang",
      name_pinyin_trad: "Wu Wang",
      stack_zh: "下震上乾",
      explanation_zh: "元亨，利贞。其匪正有眚，不利有攸往。",
      luck_zh: "大吉，顺其自然",
      sign_zh: "大吉",
      name_en_meaning: "Innocence",
      stack_en: "Bottom zhen Top qian",
      explanation_en: "Heaven over Thunder, natural innocence.",
      luck_en: "Success through authenticity and naturalness.",
      sign_en: "Very Auspicious",
    ),

    // 101000 - 101111: 下离上...
    '101000': Gua64Details(
      binary: '101000',
      symbol: '䷣', 
      name_zh: "明夷",
      name_pinyin_std: "mingyi",
      name_pinyin_trad: "Ming I",
      stack_zh: "下离上坤",
      explanation_zh: "利艰贞。",
      luck_zh: "大凶，晦暗守正",
      sign_zh: "大凶",
      name_en_meaning: "Darkening of the Light",
      stack_en: "Bottom li Top kun",
      explanation_en: "Earth over Fire, light obscured.",
      luck_en: "Patience and caution in adversity.",
      sign_en: "Very Inauspicious",
    ),
    '101001': Gua64Details(
      binary: '101001',
      symbol: '䷕',
      name_zh: "贲",
      name_pinyin_std: "bi",
      name_pinyin_trad: "Pi",
      stack_zh: "下离上艮",
      explanation_zh: "亨，小利有攸往。",
      luck_zh: "小吉，文饰之道",
      sign_zh: "小吉",
      name_en_meaning: "Grace",
      stack_en: "Bottom li Top gen",
      explanation_en: "Mountain over Fire, adornment and grace.",
      luck_en: "Success through grace and appropriate adornment.",
      sign_en: "Slightly Auspicious",
    ),
    '101010': Gua64Details(
      binary: '101010',
      symbol: '䷾',
      name_zh: "既济",
      name_pinyin_std: "jiji",
      name_pinyin_trad: "Chi Chi",
      stack_zh: "下离上坎",
      explanation_zh: "亨小利贞，初吉终乱。",
      luck_zh: "小吉，事成守成",
      sign_zh: "小吉",
      name_en_meaning: "After Completion",
      stack_en: "Bottom li Top kan",
      explanation_en: "Water over Fire, completion achieved.",
      luck_en: "Success achieved but must guard against decline.",
      sign_en: "Slightly Auspicious",
    ),
    '101011': Gua64Details(
      binary: '101011',
      symbol: '䷤',
      name_zh: "家人",
      name_pinyin_std: "jiaren",
      name_pinyin_trad: "Chia Jen",
      stack_zh: "下离上巽",
      explanation_zh: "利女贞。",
      luck_zh: "吉，家庭和睦",
      sign_zh: "吉",
      name_en_meaning: "Family",
      stack_en: "Bottom li Top xun",
      explanation_en: "Wind over Fire, family harmony.",
      luck_en: "Success through family harmony and domestic order.",
      sign_en: "Auspicious",
    ),
    '101100': Gua64Details(
      binary: '101100',
      symbol: '䷶', 
      name_zh: "丰",
      name_pinyin_std: "feng",
      name_pinyin_trad: "Feng",
      stack_zh: "下离上震",
      explanation_zh: "亨，王假之，勿忧，宜日中。",
      luck_zh: "吉，丰大易暗",
      sign_zh: "吉",
      name_en_meaning: "Abundance",
      stack_en: "Bottom li Top zhen",
      explanation_en: "Thunder over Fire, great abundance.",
      luck_en: "Great abundance and prosperity at the peak.",
      sign_en: "Auspicious",
    ),
    '101101': Gua64Details(
      binary: '101101',
      symbol: '䷝',
      name_zh: "离",
      name_pinyin_std: "li",
      name_pinyin_trad: "Li",
      stack_zh: "下离上离",
      explanation_zh: "利贞，亨。畜牝牛，吉。",
      luck_zh: "吉，依附光明",
      sign_zh: "吉",
      name_en_meaning: "The Clinging",
      stack_en: "Bottom li Top li",
      explanation_en: "Fire over Fire, clinging to clarity.",
      luck_en: "Success through clarity and conscious awareness.",
      sign_en: "Auspicious",
    ),
    '101110': Gua64Details(
      binary: '101110',
      symbol: '䷰', 
      name_zh: "革",
      name_pinyin_std: "ge",
      name_pinyin_trad: "Ge",
      stack_zh: "下离上兑",
      explanation_zh: "己日乃孚。元亨利贞。悔亡。",
      luck_zh: "吉凶未定，事多变动",
      sign_zh: "平",
      name_en_meaning: "Revolution",
      stack_en: "Bottom li Top dui",
      explanation_en: "Fire over Lake, revolution and change.",
      luck_en: "Success through timely revolution and change.",
      sign_en: "Neutral",
    ),
    '101111': Gua64Details(
      binary: '101111',
      symbol: '䷌',  
      name_zh: "同人",
      name_pinyin_std: "tongren",
      name_pinyin_trad: "T'ung Jen",
      stack_zh: "下离上乾",
      explanation_zh: "同人于野，亨，利涉大川，利君子贞。",
      luck_zh: "大吉，与人协同",
      sign_zh: "大吉",
      name_en_meaning: "Fellowship",
      stack_en: "Bottom li Top qian",
      explanation_en: "Heaven over Fire, fellowship and union.",
      luck_en: "Success through fellowship and shared goals.",
      sign_en: "Very Auspicious",
    ),

    // 110000 - 110111: 下兑上...
    '110000': Gua64Details(
      binary: '110000',
      symbol: '䷒', 
      name_zh: "临",
      name_pinyin_std: "lin",
      name_pinyin_trad: "Lin",
      stack_zh: "下兑上坤",
      explanation_zh: "元亨，利贞。至于八月有凶。",
      luck_zh: "大吉，临下思危",
      sign_zh: "大吉",
      name_en_meaning: "Approach",
      stack_en: "Bottom dui Top kun",
      explanation_en: "Earth over Lake, approach and supervision.",
      luck_en: "Success through approachability and supervision.",
      sign_en: "Very Auspicious",
    ),
    '110001': Gua64Details(
      binary: '110001',
      symbol: '䷨', 
      name_zh: "损",
      name_pinyin_std: "sun",
      name_pinyin_trad: "Sun",
      stack_zh: "下兑上艮",
      explanation_zh: "有孚，元吉，无咎，可贞，利有攸往。",
      luck_zh: "吉，损下益上",
      sign_zh: "吉",
      name_en_meaning: "Decrease",
      stack_en: "Bottom dui Top gen",
      explanation_en: "Mountain over Lake, decrease and sacrifice.",
      luck_en: "Gain through sacrifice and letting go.",
      sign_en: "Auspicious",
    ),
    '110010': Gua64Details(
      binary: '110010',
      symbol: '䷻', 
      name_zh: "节",
      name_pinyin_std: "jie",
      name_pinyin_trad: "Chieh",
      stack_zh: "下兑上坎",
      explanation_zh: "亨。苦节不可贞。",
      luck_zh: "吉，节制有度",
      sign_zh: "吉",
      name_en_meaning: "Limitation",
      stack_en: "Bottom dui Top kan",
      explanation_en: "Water over Lake, moderation and restraint.",
      luck_en: "Success through moderation and proper limits.",
      sign_en: "Auspicious",
    ),
    '110011': Gua64Details(
      binary: '110011',
      symbol: '䷼',
      name_zh: "中孚",
      name_pinyin_std: "zhongfu",
      name_pinyin_trad: "Chung Fu",
      stack_zh: "下兑上巽",
      explanation_zh: "豚鱼吉，利涉大川，利贞。",
      luck_zh: "大吉，诚信感物",
      sign_zh: "大吉",
      name_en_meaning: "Inner Truth",
      stack_en: "Bottom dui Top xun",
      explanation_en: "Wind over Lake, inner truth and sincerity.",
      luck_en: "Success through inner truth and sincerity.",
      sign_en: "Very Auspicious",
    ),
    '110100': Gua64Details(
      binary: '110100',
      symbol: '䷵', 
      name_zh: "归妹",
      name_pinyin_std: "guimei",
      name_pinyin_trad: "Kuei Mei",
      stack_zh: "下兑上震",
      explanation_zh: "征凶，无攸利。",
      luck_zh: "凶，非正之道",
      sign_zh: "凶",
      name_en_meaning: "The Marrying Maiden",
      stack_en: "Bottom dui Top zhen",
      explanation_en: "Thunder over Lake, improper union.",
      luck_en: "Caution in partnerships and unions.",
      sign_en: "Inauspicious",
    ),
    '110101': Gua64Details(
      binary: '110101',
      symbol: '䷥', 
      name_zh: "睽",
      name_pinyin_std: "kui",
      name_pinyin_trad: "K'uei",
      stack_zh: "下兑上离",
      explanation_zh: "小事吉。",
      luck_zh: "小凶，乖离缓和",
      sign_zh: "小凶",
      name_en_meaning: "Opposition",
      stack_en: "Bottom dui Top li",
      explanation_en: "Fire over Lake, opposition and divergence.",
      luck_en: "Finding common ground despite differences.",
      sign_en: "Slightly Inauspicious",
    ),
    '110110': Gua64Details(
      binary: '110110',
      symbol: '䷹', 
      name_zh: "兑",
      name_pinyin_std: "dui",
      name_pinyin_trad: "Tui",
      stack_zh: "下兑上兑",
      explanation_zh: "亨，利贞。",
      luck_zh: "吉，欣悦致亨",
      sign_zh: "吉",
      name_en_meaning: "The Joyous",
      stack_en: "Bottom dui Top dui",
      explanation_en: "Lake over Lake, joy and communication.",
      luck_en: "Satisfaction through communication and joy.",
      sign_en: "Auspicious",
    ),
    '110111': Gua64Details(
      binary: '110111',
      symbol: '䷉', 
      name_zh: "履",
      name_pinyin_std: "lv",
      name_pinyin_trad: "Lu",
      stack_zh: "下兑上乾",
      explanation_zh: "履虎尾，不咥人，亨。",
      luck_zh: "吉，谨慎行事",
      sign_zh: "吉",
      name_en_meaning: "Treading",
      stack_en: "Bottom dui Top qian",
      explanation_en: "Heaven over Lake, careful treading.",
      luck_en: "Success through careful action and practice.",
      sign_en: "Auspicious",
    ),

    // 111000 - 111111: 下乾上...
    '111000': Gua64Details(
      binary: '111000',
      symbol: '䷊', 
      name_zh: "泰",
      name_pinyin_std: "tai",
      name_pinyin_trad: "T'ai",
      stack_zh: "下乾上坤",
      explanation_zh: "小往大来，吉亨。",
      luck_zh: "大吉，天地交泰",
      sign_zh: "大吉",
      name_en_meaning: "Peace",
      stack_en: "Bottom qian Top kun",
      explanation_en: "Earth over Heaven, peace and harmony.",
      luck_en: "Great success through harmony and balance.",
      sign_en: "Very Auspicious",
    ),
    '111001': Gua64Details(
      binary: '111001',
      symbol: '䷙', 
      name_zh: "大畜",
      name_pinyin_std: "daxu",
      name_pinyin_trad: "Ta Hsü",
      stack_zh: "下乾上艮",
      explanation_zh: "利贞，不家食吉，利涉大川。",
      luck_zh: "大吉，大有积蓄",
      sign_zh: "大吉",
      name_en_meaning: "Great Accumulation",
      stack_en: "Bottom qian Top gen",
      explanation_en: "Mountain over Heaven, great accumulation.",
      luck_en: "Success through accumulation and preparation.",
      sign_en: "Very Auspicious",
    ),
    '111010': Gua64Details(
      binary: '111010',
      symbol: '䷄', 
      name_zh: "需",
      name_pinyin_std: "xu",
      name_pinyin_trad: "Hsü",
      stack_zh: "下乾上坎",
      explanation_zh: "有孚，光亨，贞吉，利涉大川。",
      luck_zh: "吉，等待时机",
      sign_zh: "吉",
      name_en_meaning: "Waiting",
      stack_en: "Bottom qian Top kan",
      explanation_en: "Water over Heaven, waiting with patience.",
      luck_en: "Success through patience and proper timing.",
      sign_en: "Auspicious",
    ),
    '111011': Gua64Details(
      binary: '111011',
      symbol: '䷈',  
      name_zh: "小畜",
      name_pinyin_std: "xiaoxu",
      name_pinyin_trad: "Hsiao Hsü",
      stack_zh: "下乾上巽",
      explanation_zh: "亨。密云不雨，自我西郊。",
      luck_zh: "小亨，小有积蓄",
      sign_zh: "小吉",
      name_en_meaning: "Small Accumulation",
      stack_en: "Bottom qian Top xun",
      explanation_en: "Wind over Heaven, small accumulation.",
      luck_en: "Small gains through modest accumulation.",
      sign_en: "Slightly Auspicious",
    ),
    '111100': Gua64Details(
      binary: '111100',
      symbol: '䷡', 
      name_zh: "大壮",
      name_pinyin_std: "dazhuang",
      name_pinyin_trad: "Ta Chuang",
      stack_zh: "下乾上震",
      explanation_zh: "利贞。",
      luck_zh: "吉，盛壮守礼",
      sign_zh: "吉",
      name_en_meaning: "Great Power",
      stack_en: "Bottom qian Top zhen",
      explanation_en: "Thunder over Heaven, great strength.",
      luck_en: "Powerful but must be used with restraint.",
      sign_en: "Auspicious",
    ),
    '111101': Gua64Details(
      binary: '111101',
      symbol: '䷍', 
      name_zh: "大有",
      name_pinyin_std: "dayou",
      name_pinyin_trad: "Ta Yu",
      stack_zh: "下乾上离",
      explanation_zh: "元亨。",
      luck_zh: "大吉，大获所有",
      sign_zh: "大吉",
      name_en_meaning: "Great Possession",
      stack_en: "Bottom qian Top li",
      explanation_en: "Fire over Heaven, great possession.",
      luck_en: "Great abundance and possession.",
      sign_en: "Very Auspicious",
    ),
    '111110': Gua64Details(
      binary: '111110',
      symbol: '䷪', 
      name_zh: "夬",
      name_pinyin_std: "guai",
      name_pinyin_trad: "Kuai",
      stack_zh: "下乾上兑",
      explanation_zh: "扬于王庭，孚号有厉，告自邑，不利即戎，利有攸往。",
      luck_zh: "吉，果断决策",
      sign_zh: "吉",
      name_en_meaning: "Resolution",
      stack_en: "Bottom qian Top dui",
      explanation_en: "Lake over Heaven, decisiveness and resolution.",
      luck_en: "Success through decisive action and resolution.",
      sign_en: "Auspicious",
    ),
    '111111': Gua64Details(
      binary: '111111',
      symbol: '䷀',  // U+4DFF
      name_zh: "乾",
      name_pinyin_std: "qian",
      name_pinyin_trad: "Ch'ien",
      stack_zh: "下乾上乾",
      explanation_zh: "元亨，利贞。",
      luck_zh: "大吉，纯阳至健",
      sign_zh: "大吉",
      name_en_meaning: "The Creative",
      stack_en: "Bottom qian Top qian",
      explanation_en: "Heaven over Heaven, ultimate creative force.",
      luck_en: "Supreme success through creativity and strength.",
      sign_en: "Very Auspicious",
    ),
  };

  /// Retrieves the 64 Gua details based on the 6-round binary result.
  static Gua64Details? get64Gua(String binary) {
    // Expects a 6-character binary string ('111000')
    if (binary.length != 6 || !Gua64Map.containsKey(binary)) {
      return null;
    }
    return Gua64Map[binary];
  }
}